//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rebirth.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rebirth.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /*
        ///Navicat MySQL Data Transfer
        ///
        ///Source Server         : localhost
        ///Source Server Version : 50714
        ///Source Host           : localhost:3306
        ///Source Database       : auth
        ///
        ///Target Server Type    : MYSQL
        ///Target Server Version : 50714
        ///File Encoding         : 65001
        ///
        ///Date: 2017-06-03 10:36:15
        ///*/
        ///
        ///SET FOREIGN_KEY_CHECKS=0;
        ///
        ///-- ----------------------------
        ///-- Table structure for accounts
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS `accounts`;
        ///CREATE TABLE `accounts` (
        ///  `Id` int(11) NOT NUL [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string auth {
            get {
                return ResourceManager.GetString("auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /*
        ///Navicat MySQL Data Transfer
        ///
        ///Source Server         : localhost
        ///Source Server Version : 50714
        ///Source Host           : localhost:3306
        ///Source Database       : world
        ///
        ///Target Server Type    : MYSQL
        ///Target Server Version : 50714
        ///File Encoding         : 65001
        ///
        ///Date: 2017-06-03 10:36:28
        ///*/
        ///
        ///SET FOREIGN_KEY_CHECKS=0;
        ///
        ///-- ----------------------------
        ///-- Table structure for alliances
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS `alliances`;
        ///CREATE TABLE `alliances` (
        ///  `Id` int(10) uns [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string world {
            get {
                return ResourceManager.GetString("world", resourceCulture);
            }
        }
    }
}
